name: Install ArgoCD on Alpine

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install-argocd:
    runs-on: [self-hosted]  # targets your self-hosted runner
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies in runner pod
        run: |
          yum install -y curl bash git

      - name: Download ArgoCD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd

      - name: Verify
        run: argocd version --client
