name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - 'Dockerfile'
      - '.github/workflows/docker-build.yml'
  pull_request:
    branches:
      - main
env:
  REGISTRY: quay.io
  # or use: ghcr.io (GitHub Container Registry)
  IMAGE_NAME: your-org/your-app
  IMAGE_TAG: ${{ github.sha }}
jobs:
  build:
    runs-on: [self-hosted, okd, prod]
    container:
      image: moby/buildkit:v0.23.1-rootless
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}   # used only as a local image name
      CONTEXT_PATH: ./                           # adjust as needed
      DOCKERFILE_PATH: ./Dockerfile             # adjust as needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup BuildKit
        run: |
          echo "🛠️ Preparing BuildKit environment"

      - name: Build Docker image locally
        run: |
          echo "🛠️ Build Docker image from $DOCKERFILE_PATH in context $CONTEXT_PATH"
          buildctl-daemonless.sh build \
            --frontend=dockerfile.v0 \
            --local context="$CONTEXT_PATH" \
            --local dockerfile="$(dirname "$DOCKERFILE_PATH")" \
            --opt filename="$(basename "$DOCKERFILE_PATH")" \
            --output type=image,name="$DOCKER_IMAGE",push=false

