name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - 'Dockerfile'
      - '.github/workflows/docker-build.yml'
  pull_request:
    branches:
      - main
env:
  REGISTRY: quay.io
  # or use: ghcr.io (GitHub Container Registry)
  IMAGE_NAME: your-org/your-app
  IMAGE_TAG: ${{ github.sha }}
jobs:
  build:
    runs-on: [self-hosted, okd, prod]             # adjust as needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ArgoCD CLI
        uses: alpine
        run: |
          apk add --no-cache curl jq bash >/dev/null 2>&1 \
          && curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/v3.0.0/argocd-linux-amd64 \
          && chmod +x /usr/local/bin/argocd \
          && argocd version
