name: Install ArgoCD on Alpine

on:
  workflow_dispatch:  # manual trigger for testing

jobs:
  install-argocd:
    runs-on: [self-hosted]  # targets your self-hosted runner
    container:
      image: alpine:3.18   # run job inside Alpine container
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apk add --no-cache curl bash git

      - name: Download ArgoCD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd

      - name: Verify ArgoCD installation
        run: argocd version --client