name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - 'Dockerfile'
      - '.github/workflows/docker-build.yml'
  pull_request:
    branches:
      - main
env:
  REGISTRY: quay.io
  # or use: ghcr.io (GitHub Container Registry)
  IMAGE_NAME: your-org/your-app
  IMAGE_TAG: ${{ github.sha }}
jobs:
  build:
    runs-on: [self-hosted, okd, prod]             # adjust as needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OpenShift CLI (oc)
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
          tar -xzf openshift-client-linux.tar.gz
          chmod +x oc kubectl
          mv oc kubectl /usr/local/bin/

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          mv argocd /usr/local/bin/

      - name: Show versions
        run: |
          echo "OC version:"
          oc version
          echo "Kubectl version:"
          kubectl version --client
          echo "ArgoCD version:"
          argocd version
